### ISSUE TITLE
Saving Profile Skip Entry Bug

### ISSUE THREAD

**Issue by stevens4** [ekajmiller/magicleague#1]
saving profile button click will skip player profile being viewed to either the last entry or #19 (from #17)

**Comment by sn1kketysnake** [comment]
Thanks Stevens. I know what this is.

**Comment by sn1kketysnake** [comment]
Should now be fixed with 2879b3e291954045418dec9d22d080458abbc2fb. Please test.

**Comment by stevens4** [comment]
Still not fixed. Edit profile > click update > land on Razik's profile.
